<?php

use Illuminate\Database\Seeder;

use App\Models\Beers\Style;

class BeerStyleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $styles = [
            "Classic English-Style Pale Ale",
            "English-Style India Pale Ale",
            "Ordinary Bitter",
            "Special Bitter or Best Bitter",
            "Extra Special Bitter",
            "English-Style Summer Ale",
            "Scottish-Style Light Ale",
            "Scottish-Style Heavy Ale",
            "Scottish-Style Export Ale",
            "English-Style Pale Mild Ale",
            "English-Style Dark Mild Ale",
            "English-Style Brown Ale",
            "Old Ale",
            "Strong Ale",
            "Scotch Ale",
            "British-Style Imperial Stout",
            "British-Style Barley Wine Ale",
            "Robust Porter",
            "Brown Porter",
            "Sweet Stout",
            "Oatmeal Stout",
            "Irish-Style Red Ale",
            "Classic Irish-Style Dry Stout",
            "Foreign (Export)-Style Stout",
            "Porter",
            "American-Style Pale Ale",
            "Fresh Hop Ale",
            "Pale American-Belgo-Style Ale",
            "Dark American-Belgo-Style Ale",
            "American-Style Strong Pale Ale",
            "American-Style India Pale Ale",
            "Imperial or Double India Pale Ale",
            "American-Style Amber/Red Ale",
            "Imperial or Double Red Ale",
            "American-Style Barley Wine Ale",
            "American-Style Wheat Wine Ale",
            "Golden or Blonde Ale",
            "American-Style Brown Ale",
            "Smoke Porter",
            "American-Style Sour Ale",
            "American-Style India Black Ale",
            "American-Style Stout",
            "American-Style Imperial Stout",
            "Specialty Stouts",
            "American-Style Imperial Porter",
            "Porter",
            "German-Style Kolsch",
            "Berliner-Style Weisse",
            "Leipzig-Style Gose",
            "South German-Style Hefeweizen",
            "South German-Style Kristal Weizen",
            "German-Style Leichtes Weizen",
            "South German-Style Bernsteinfarbenes Weizen",
            "South German-Style Dunkel Weizen",
            "South German-Style Weizenbock",
            "Bamberg-Style Weiss Rauchbier",
            "German-Style Brown Ale/Altbier",
            "Kellerbier - Ale",
            "Belgian-Style Flanders/Oud Bruin",
            "Belgian-Style Dubbel",
            "Belgian-Style Tripel",
            "Belgian-Style Quadrupel",
            "Belgian-Style Blonde Ale",
            "Belgian-Style Pale Ale",
            "Belgian-Style Pale Strong Ale",
            "Belgian-Style Dark Strong Ale",
            "Belgian-Style White",
            "Belgian-Style Lambic",
            "Belgian-Style Gueuze Lambic", 
            "Belgian-Style Fruit Lambic",
            "Belgian-Style Table Beer",
            "Other Belgian-Style Ales",
            "French-Style Biere de Garde",
            "French & Belgian-Style Saison",
            "International-Style Pale Ale",
            "Australasian-Style Pale Ale",
            "German-Style Pilsener",
            "Bohemian-Style Pilsener",
            "European Low-Alcohol Lager",
            "Munchner-Style Helles",
            "Dortmunder/European-Style Export",
            "Vienna-Style Lager",
            "German-Style Marzen",
            "German-Style Oktoberfest",
            "European-Style Dark",
            "German-Style Schwarzbier",
            "Bamberg-Style Marzen",
            "Bamberg-Style Helles Rauchbier",
            "Bamberg-Style Bock Rauchbier",
            "Traditional German-Style Bock",
            "German-Style Heller Bock/Maibock",
            "German-Style Doppelbock",
            "German-Style Eisbock",
            "Kellerbier - Lager",
            "American-Style Lager",
            "American-Style Light Lager",
            "American-Style Low-Carb Light Lager",
            "American-Style Amber Lager",
            "American-Style Premium Lager",
            "American-Style Pilsener",
            "American-Style Ice Lager",
            "American-Style Malt Liquor",
            "American-Style Amber Lager",
            "American-Style Marzen/Oktoberfest",
            "American-Style Dark Lager",
            "Baltic-Style Porter",
            "Australasian-Style Light Lager",
            "Latin American-Style Light Lager",
            "Tropical-Style Light Lager",
            "International-Style Pilsener",
            "Dry Lager",
            "Session Beer",
            "American-Style Cream Ale or Lager",
            "California Common Beer",
            "Japanese Sake-Yeast Beer",
            "Light American Wheat Ale or Lager",
            "Fruit Wheat Ale or Lager",
            "Dark American Wheat Ale or Lager",
            "American Rye Ale or Lager",
            "German-Style Rye Ale",
            "Fruit Beer",
            "Field Beer",
            "Pumpkin Beer",
            "Chocolate/Cocoa-Flavored Beer",
            "Coffee-Flavored Beer",
            "Herb and Spice Beer",
            "Specialty Beer",
            "Specialty Honey Lager or Ale",
            "Gluten-Free Beer",
            "Smoke Beer",
            "Aged Beer",
            "Non-Alcoholic Beer",
            "Winter Warmer",
        ];

        foreach ($styles as $style) {
            Style::create([
                'name' => $style,
            ]);
        }
    }
}
